### ISSUE TITLE
🐞 [Bug] : Error in creating new tab in editor with prefilled Microsoft 365 CLI Script

### ISSUE THREAD

**Issue by Saurabh7019** [Adam-it/cli-for-microsoft-365-extension#67]
### 📝 Describe the bug
Error occurs when selecting a script in CLI for Microsoft 365 VS Code Extension samples: 'Error while creating script file based on sample.

### 👣 Steps To Reproduce
1. Open the CLI for Microsoft 365 extension in Visual Studio Code.
2. Select the "CLI for Microsoft 365 Samples" option.
3. Click on the "Script" button on a sample tile.

### 📜 Expected behavior
A new tab should open in Visual Studio Code, and the corresponding script should load within that tab.

### 📷 Screenshots
![image](https://github.com/Adam-it/cli-for-microsoft-365-extension/assets/18114579/fd2f2778-b774-4224-8024-e9e9bd90d7ed)

### 💻 Desktop (please complete the following information):
 - OS: Windows 11 Enterprise

**Comment by Adam-it** [comment]
@Saurabh7019 thanks for the feedback. I already know what is the issue, since in CLI for M365 we migrated docs from mkdocs do docusource and there is a slightly different format in the way we now store samples. 
As the extensions just 'cuts out' the script from sample file from the repo probably the way I split the sample is currently not valid anymore.

So additional info is that this bug will only happen for script samples coming from CLI repo bit from PnP script samples repo (that's why probably I did not notice it during testing 🤦‍♂️)

I planned to spend some time today on this extensions so I will look into this bug ASAP. 👍

**Comment by Saurabh7019** [comment]
No rush! I just wanted to bring it to your attention.

**Comment by Adam-it** [comment]
@Saurabh7019 BTW, I know it's not part of this issue so if you want we could move this to some different chat or any other place, but from the screen shoot I noticed you also have the Viva Connections Toolkit 👀. TBH I am looking for some feedback on this extension and I was wondering if you would be so kind and maybe you could share some comments or observations about this extension? Do you see something lacking or not useful? Any kind of feedback will be helpful ♥️

**Comment by Saurabh7019** [comment]
Absolutely! I would be happy to thoroughly explore the extension and provide you with my observations and any suggestions for improvement.

**Comment by Adam-it** [comment]
> Absolutely! I would be happy to thoroughly explore the extension and provide you with my observations and any suggestions for improvement.

Thanks, you rock 🤩. Reach me out or open an issue on the Viva vs code extension 👍. I will keep an eye out for your feedback
